services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MODE: development
    ports:
      - 8080:8080
    depends_on:
      - api
    develop:
      watch:
        - path: .
          target: /usr/share/nginx/html/
          action: sync
        - path: ./conf.d/
          target: /etc/nginx/conf.d/
          action: rebuild
    env_file:
      - ./.env

  api:
    build:
      context: ./libs/php
      dockerfile: Dockerfile
      args:
        USERNAME: ${USERNAME}
        IPINFO_TOKEN: ${IPINFO_TOKEN}
        JAWG_TOKEN: ${JAWG_TOKEN}
        MODE: development
    ports:
      - 9000:9000
    develop:
      watch:
        - path: ./libs/php
          target: /var/www/html/
          action: sync
    env_file:
      - ./.env
